import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import { inter } from '@/app/ui/fonts'
import AuthProvider from "@/app/components/auth_provider"
import Header from "@/app/ui/header/header"
import Footer from "@/app/ui/footer/footer"
import {SkeletonTheme} from "react-loading-skeleton"
import 'react-loading-skeleton/dist/skeleton.css'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          className={`${inter.className} antialiased\``}
      >
          <SkeletonTheme baseColor="#cfcfcf" highlightColor="#edebeb">
            <AuthProvider>
                <Header />
                {children}
                <Footer />
            </AuthProvider>
          </SkeletonTheme>
      </body>
    </html>
  );
}
