export const LINK_MAIN = '/'
export const LINK_PROFILE = '/profile'
export const LINK_REGISTRATION = '/auth/register'
export const LINK_LOGIN = '/auth/login'
export const LINK_FUNDRAISES = '/fundraise'
export const LINK_NEWS = '/news'
export const LINK_ARM_MERCHANTS = '/arm/merchants'
export const LINK_ARM_CAMPAIGNS = '/arm/campaigns'

export const ROLE_USER = 'user'
export const ROLE_MERCHANT = 'merchant'
export const ROLE_ADMIN = 'admin'